import "./globals.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}

/// remember thats only deferent things in the world caused remastered
/// never caused daver sting uri reconfirmed side by siede thats cause dens
///
/// chaster dabbs basterd gasturbine
///
/// sad buit jkak nde has k namx ehamdb
